name: Android CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - name: set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Build with Gradle
#       run: ./gradlew build
    - name: Decrypt large secret
      run: 'gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_JSON_KEY  }}" --output ./app/google-services.json ./app/google-services.json.gpg'
    - name: Test printing your secret (Remove this step in production)
      run: cat ./app/google-services.json
