name: Android CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Decrypt json file
      run: 'gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_JSON_KEY  }}" --output ./app/google-services.json ./app/google-services.json.gpg'
    - name: Decrypt jks file
      run: 'gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_JSON_KEY  }}" --output ./signkey.jks.gpg ./signkey.jks'
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDevRelease
